printWidth: 120
useTabs: true
tabWidth: 5
semi: true
singleQuote: true
quoteProps: as-needed
endOfLine: crlf
overrides:
  - files:
      - "*.yml"
      - "*.yaml"
    options:
      printWidth: 100
      singleQuote: false
